version: "3"
services:
  warsow:
    build:
      dockerfile: Dockerfile
    ports:
      - "44400:44400"
      - "44444:44444"
    network_mode: host
    volumes:
      - ./dedicated_autoexec.cfg:/opt/warsow-2.1.2/basewsw/dedicated_autoexec.cfg
